### ISSUE TITLE
watch is not working

### ISSUE THREAD

**Issue by sadeghbarati** [lukeed/is-offline#2]
the only trigger once 
and after disable net `watch` function not working for new `console.log`

**Comment by lukeed** [comment]
Hey, it works fine for me: https://jsfiddle.net/lukeed/8at2tg1e/

Are you sure there's not something else removing/detaching the instance?

**Comment by sadeghbarati** [comment]
I'm using this package in pure HTML5 and JS project no NPM

but seem its not working

**Comment by sadeghbarati** [comment]
``` javascript 
    const isOffline = window['is-offline'];

    function listen(fn, action) {
        action = window[action + 'EventListener'];
        action('offline', fn);
        action('online', fn);
    }

    function check() {
        return Promise.resolve(!navigator.onLine);
    }

    function watch(cb) {
        function checker() {
            return check().then(cb);
        }
        listen(checker, 'add');
        return function () {
            listen(checker, 'remove');
        };
    }

    var foobar = function foobar(bool) {
        return console.log('Am I offline?', bool);
    }; // Check if currently offline


    isOffline.check().then(foobar); // Setup a "watcher" to respond to all online/offline changes

    var unwatch = isOffline.watch(foobar);
    unwatch();
```

**Comment by lukeed** [comment]
Ok. The `check` is meant for single, immediate lookups. The `watch` is meant to be like an event listener, basically.

The reason you see it happening once is because of `check`. Your `watch` is doing absolutely nothing because you immediately cancel/dismiss it by calling `unwatch`.

If you want watch to work, you're going to have to let it live for a while.

Hope that helps
